required = [
  "k8s.io/code-generator/cmd/defaulter-gen",
  "k8s.io/code-generator/cmd/deepcopy-gen",
  "k8s.io/code-generator/cmd/conversion-gen",
  "k8s.io/code-generator/cmd/client-gen",
  "k8s.io/code-generator/cmd/lister-gen",
  "k8s.io/code-generator/cmd/informer-gen"
]

[[override]]
  name = "github.com/gardener/gardener-extensions"
  revision = "946f575a6489de2c884973e27d0e15ca66ab96c5"

[[override]]
  name = "github.com/gardener/gardener"
  revision = "f718e4bd65f08a62a8fa7836dcebb8e7d2476c1e"

[[override]]
  name = "github.com/pkg/errors"
  revision = "816c9085562cd7ee03e7f8188a1cfd942858cded"

[[override]]
  name = "github.com/gardener/machine-controller-manager"
  revision = "119056ee3fddc24a33b206ba89958da30535bd02"

[[override]]
  name = "sigs.k8s.io/controller-runtime"
  version = "0.1.10"

[[override]]
  name = "k8s.io/api"
  version = "kubernetes-1.13.4"

[[override]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.13.4"

[[override]]
  name = "k8s.io/apiserver"
  version = "kubernetes-1.13.4"

[[override]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.13.4"

[[override]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.13.4"

[[override]]
  name = "k8s.io/code-generator"
  version = "kubernetes-1.13.4"

[[override]]
  name = "k8s.io/kube-aggregator"
  version = "kubernetes-1.13.4"

[[override]]
  name = "k8s.io/kubelet"
  version = "kubernetes-1.13.4"

# use the same version that is referenced by k8s.io/apiserver
[[override]]
  name = "github.com/docker/docker"
  revision = "a9fbbdc8dd8794b20af358382ab780559bca589d"

# use the same version that is referenced by k8s.io, mainly required by Helm
# https://github.com/kubernetes/kubernetes/blob/v1.13.5/Godeps/Godeps.json
[[override]]
  name = "github.com/russross/blackfriday"
  revision = "300106c228d52c8941d4b3de6054a6062a86dda3"

[[override]]
  name = "github.com/jmespath/go-jmespath"
  version = "^0.2.2"

[[constraint]]
  name = "github.com/packethost/packngo"
  revision = "b3b45f1b4979af3ace1cd5450768ab387b40ae5b"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[[constraint]]
  name = "github.com/gobuffalo/packr"
  version = "1.21.9"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "golang.org/x/oauth2"
  revision = "c85d3e98c914e3a33234ad863dcbff5dbc425bb8"

[[constraint]]
  name = "google.golang.org/api"
  version = "0.2.0"

[[constraint]]
  name = "github.com/coreos/go-systemd"
  version = "v19"

# Dependencies for testing purposes only

[[constraint]]
  name = "github.com/onsi/gomega"
  version = "~1.3.0"

[[constraint]]
  name = "github.com/onsi/ginkgo"
  version = "~1.4.0"

[[constraint]]
  name = "github.com/golang/mock"
  version = "1.2.0"

[prune]
  unused-packages = true
  go-tests = true
  non-go = true

  [[prune.project]]
    name = "k8s.io/code-generator"
    unused-packages = false
    non-go = false

  [[prune.project]]
    name = "github.com/golang/mock"
    unused-packages = false