---
#
# Deployment, deploys webhook in Shoot-Controlplane
#
# MUST BE CONFIGURED FOR CLUSTER / TENANT / TRUSTED TOKEN ISSUER
#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-jwt-authn-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    k8s-app: kube-jwt-authn-webhook
spec:
  selector:
    matchLabels:
      k8s-app: kube-jwt-authn-webhook
  template:
    metadata:
      labels:
        k8s-app: kube-jwt-authn-webhook
        app: kube-jwt-authn-webhook
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
    spec:
      containers:
      - image: {{ index .Values.images "authn-webhook" }}
        name: kubernetes-authn-webhook
        ports:
        - containerPort: 3000
          protocol: TCP
        env:
        - name: ISSUER
          value: {{ .Values.authn_oidcIssuerUrl }}
        - name: CLIENTID
          value: {{ .Values.authn_oidcIssuerClientId }}
        - name: GROUPSPREFIXTOREMOVE
          value: k8s
        - name: TENANT
          value: {{ .Values.authn_tenant }}
        - name: CLUSTER
          value: {{ .Values.authn_clustername }}
        - name: DEBUG
          value: {{ quote .Values.authn_debug }}
      restartPolicy: Always
