apiVersion: apps/v1
kind: Deployment
metadata:
  name: limit-validating-webhook
  namespace: {{ .Release.Namespace }}
  labels:
    app: limit-validating-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: limit-validating-webhook
  template:
    metadata:
      labels:
        k8s-app: limit-validating-webhook
        app: limit-validating-webhook
        networking.gardener.cloud/from-prometheus: allowed
        networking.gardener.cloud/to-dns: allowed
        networking.gardener.cloud/to-shoot-apiserver: allowed
        networking.gardener.cloud/to-public-networks: allowed
      annotations:
        scheduler.alpha.kubernetes.io/critical-pod: ''
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '2112'
    spec:
      containers:
        - name: limit-validating-webhook
          image: {{ index .Values.images "limit-validating-webhook" }}
          imagePullPolicy: Always
          ports:
          - containerPort: 443
            protocol: TCP
          args:
            - -tlsCertFile=/etc/webhook/certs/limit-validating-webhook-server.crt
            - -tlsKeyFile=/etc/webhook/certs/limit-validating-webhook-server.key
            - -excludedNamespaces=kube-system
            - -enforceResourceRequests=false
            - -enforceResourceLimits={{ .Values.lvw_validate }}
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
      volumes:
        - name: webhook-certs
          secret:
            secretName: limit-validating-webhook-server

---
apiVersion: v1
kind: Service
metadata:
    name: limit-validating-webhook
    namespace: {{ .Release.Namespace }}
    labels:
        app: limit-validating-webhook
spec:
    selector:
        app: limit-validating-webhook
    ports:
    - port: 443
      targetPort: 443

---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
    name: limit-validating-webhook-allow-namespace
    namespace: {{ .Release.Namespace }}
spec:
    podSelector:
        matchLabels:
            app: limit-validating-webhook
    ingress:
    - from:
      - podSelector:
            matchLabels:
                app: kubernetes
                role: apiserver

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
    name: kubeapi2limit-validating-webhook
    namespace: {{ .Release.Namespace }}
spec:
    egress:
    - ports:
      - port: 443
        protocol: TCP
      to:
      - podSelector:
            matchLabels:
                app: limit-validating-webhook
    podSelector:
        matchLabels:
            app: kubernetes
            role: apiserver
    policyTypes:
    - Egress
