images:
- name: metalccm
  sourceRepository: docker.io/metalpod/metal-ccm
  repository: metalpod/metal-ccm
  tag: latest
- name: machine-controller-manager
  sourceRepository: github.com/gardener/machine-controller-manager
  repository: eu.gcr.io/gardener-project/gardener/machine-controller-manager
  tag: "0.19.0-dev"
- name: etcd-backup-restore
  sourceRepository: github.com/gardener/etcd-backup-restore
  repository: eu.gcr.io/gardener-project/gardener/etcdbrctl
  tag: "0.6.4"
- name: droptailer
  sourceRepository: metal-pod/droptailer
  repository: docker.io/metalpod/droptailer-server
  tag: latest
- name: csi-lvm-controller
  sourceRepository: github.com/metal-pod/csi-lvm-controller
  repository: metalpod/csi-lvm-controller
  tag: v0.2.2
- name: csi-lvm-provisioner
  sourceRepository: github.com/metal-pod/csi-lvm-provisioner
  repository: metalpod/csi-lvm-provisioner
  tag: v0.2.2
# can be provided via image override:
# - name: authn-webhook
#   sourceRepository:
#   repository:
#   tag:
# - name: group-rolebinding-controller
#   sourceRepository:
#   repository:
#   tag:
# - name: accounting-exporter
#   sourceRepository:
#   repository:
#   tag:
