images:
- name: metalccm
  sourceRepository: github.com/metal-stack/metal-ccm
  repository: ghcr.io/metal-stack/metal-ccm
  tag: "v0.5.5"
- name: machine-controller-manager
  sourceRepository: github.com/gardener/machine-controller-manager
  repository: eu.gcr.io/gardener-project/gardener/machine-controller-manager
  tag: "0.35.0"
- name: machine-controller-manager-provider-metal
  sourceRepository: https://github.com/metal-stack/machine-controller-manager-provider-metal
  repository: ghcr.io/metal-stack/machine-controller-manager-provider-metal
  tag: "v0.1.5"
- name: auditforwarder
  sourceRepository: https://github.com/metal-stack/audit-forwarder
  repository: ghcr.io/metal-stack/audit-forwarder
  tag: "v0.1.0"
- name: audittailer
  sourceRepository: https://github.com/fluent/fluentd
  repository: fluent/fluentd
  tag: "v1.12"
- name: droptailer
  sourceRepository: github.com/metal-stack/droptailer
  repository: ghcr.io/metal-stack/droptailer
  tag: "v0.2.5"
- name: csi-lvm-controller
  sourceRepository: github.com/metal-stack/csi-lvm-controller
  repository: ghcr.io/metal-stack/csi-lvm-controller
  tag: "v0.6.3"
- name: csi-lvm-provisioner
  sourceRepository: github.com/metal-stack/csi-lvm-provisioner
  repository: ghcr.io/metal-stack/csi-lvm-provisioner
  tag: "v0.6.3"
- name: metallb-speaker
  sourceRepository: https://github.com/metallb/metallb
  repository: quay.io/metallb/speaker
  tag: "v0.10.2"
- name: metallb-controller
  sourceRepository: https://github.com/metallb/metallb
  repository: quay.io/metallb/controller
  tag: "v0.10.2"
- name: duros-controller
  sourceRepository: https://github.com/metal-stack/duros-controller
  repository: ghcr.io/metal-stack/duros-controller
  tag: "v0.2.0"
# firewall-controller tag must be semver compatible with golang dependency!
- name: firewall-controller
  sourceRepository: https://github.com/metal-stack/firewall-controller
  tag: "v1.0.9"

# can be provided via image override:
# - name: authn-webhook
#   sourceRepository:
#   repository:
#   tag:
# - name: group-rolebinding-controller
#   sourceRepository:
#   repository:
#   tag:
# - name: accounting-exporter
#   sourceRepository:
#   repository:
#   tag:
