images:
- name: metalccm
  sourceRepository: github.com/metal-stack/metal-ccm
  repository: ghcr.io/metal-stack/metal-ccm
  tag: "v0.7.13"
- name: machine-controller-manager-provider-metal
  sourceRepository: https://github.com/metal-stack/machine-controller-manager-provider-metal
  repository: ghcr.io/metal-stack/machine-controller-manager-provider-metal
  tag: "v0.1.19"
- name: droptailer
  sourceRepository: github.com/metal-stack/droptailer
  repository: ghcr.io/metal-stack/droptailer
  tag: "v0.2.12"
- name: csi-lvm-controller
  sourceRepository: github.com/metal-stack/csi-lvm-controller
  repository: ghcr.io/metal-stack/csi-lvm-controller
  tag: "v0.7.0"
- name: csi-lvm-provisioner
  sourceRepository: github.com/metal-stack/csi-lvm-provisioner
  repository: ghcr.io/metal-stack/csi-lvm-provisioner
  tag: "v0.7.0"
- name: metallb-speaker
  sourceRepository: https://github.com/metallb/metallb
  repository: quay.io/metallb/speaker
  tag: "v0.15.2"
- name: metallb-controller
  sourceRepository: https://github.com/metallb/metallb
  repository: quay.io/metallb/controller
  tag: "v0.15.2"
- name: duros-controller
  sourceRepository: https://github.com/metal-stack/duros-controller
  repository: ghcr.io/metal-stack/duros-controller
  tag: "v0.7.2"
- name: node-init
  sourceRepository: https://github.com/metal-stack/node-init
  repository: ghcr.io/metal-stack/node-init
  tag: "v0.1.4"
- name: metallb-health-sidecar
  sourceRepository: https://github.com/metal-stack/metallb-health-sidecar
  repository: ghcr.io/metal-stack/metallb-health-sidecar
  tag: "v0.1.2"
- name: firewall-controller-manager
  sourceRepository: https://github.com/metal-stack/firewall-controller-manager
  repository: ghcr.io/metal-stack/firewall-controller-manager
  tag: "firewall-health-check"
