images:
- name: metalccm
  sourceRepository: github.com/metal-stack/metal-ccm
  repository: metalstack/metal-ccm
  tag: v0.3.0
- name: machine-controller-manager
  sourceRepository: github.com/gardener/machine-controller-manager
  repository: eu.gcr.io/gardener-project/gardener/machine-controller-manager
  tag: "0.26.3"
- name: droptailer
  sourceRepository: github.com/metal-stack/droptailer
  repository: metalstack/droptailer
  tag: v0.2.1
- name: csi-lvm-controller
  sourceRepository: github.com/metal-stack/csi-lvm-controller
  repository: metalstack/csi-lvm-controller
  tag: v0.6.0
- name: csi-lvm-provisioner
  sourceRepository: github.com/metal-stack/csi-lvm-provisioner
  repository: metalstack/csi-lvm-provisioner
  tag: v0.6.0
- name: csi-attacher
  sourceRepository: github.com/kubernetes-csi/external-attacher
  repository: quay.io/k8scsi/csi-attacher
  tag: v2.2.0
- name: csi-resizer
  sourceRepository: github.com/kubernetes-csi/external-resizer
  repository: quay.io/k8scsi/csi-resizer
  tag: v0.5.0
- name: csi-node-driver-registrar
  sourceRepository: github.com/kubernetes-csi/node-driver-registrar
  repository: quay.io/k8scsi/csi-node-driver-registrar
  tag: v1.3.0
- name: csi-provisioner
  sourceRepository: github.com/kubernetes-csi/external-provisioner
  repository: quay.io/k8scsi/csi-provisioner
  tag: v1.6.0
- name: csi-livenessprobe
  sourceRepository: github.com/kubernetes-csi/livenessprobe
  repository: quay.io/k8scsi/livenessprobe
  tag: v1.1.0
- name: csi-lvmplugin
  sourceRepository: github.com/metal-stack/csi-driver-lvm
  repository: metalstack/lvmplugin
  tag: v0.3.6
- name: csi-lvmplugin-provisioner
  sourceRepository: github.com/metal-stack/csi-driver-lvm
  repository: metalstack/csi-lvmplugin-provisioner
  tag: v0.3.6
- name: metallb-speaker
  sourceRepository: https://github.com/metallb/metallb
  repository: metallb/speaker
  tag: v0.8.3
- name: metallb-controller
  sourceRepository: https://github.com/metallb/metallb
  repository: metallb/controller
  tag: v0.8.3
- name: splunk-audit-webhook
  sourceRepository: https://github.com/metal-stack/kubernetes-splunk-audit-webhook
  repository: metalstack/kubernetes-splunk-audit-webhook
  tag: v0.1.0

# can be provided via image override:
# - name: authn-webhook
#   sourceRepository:
#   repository:
#   tag:
# - name: group-rolebinding-controller
#   sourceRepository:
#   repository:
#   tag:
# - name: accounting-exporter
#   sourceRepository:
#   repository:
#   tag:
